## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [4]:
samples = np.random.normal(100,15,1000)
samples

array([ 63.32914946,  98.40034699, 115.10708889, 103.29293904,
        85.68257523, 116.46523002,  89.99492933,  99.22932458,
       101.25284865,  98.07237195, 107.20059074,  83.64726513,
        86.00478986,  97.03847807, 118.07634779, 105.03355248,
       110.41657454, 109.34095828,  99.9961096 ,  82.70276849,
       101.68192698, 130.73319953,  85.40024242, 100.61639334,
        81.88032125, 132.33744527,  89.99555533, 104.28232207,
       107.42471821,  88.38923002, 119.52593036,  89.09439494,
        83.84680825, 104.5596799 ,  86.76849912, 116.50046187,
       110.88491483,  92.81707432, 108.23785818, 114.20625973,
       103.98167637, 124.56035795,  99.70848799, 107.85478778,
       102.43447071,  78.9469326 , 107.08288745,  92.78790714,
       104.20302947,  94.95054031,  95.22261782, 126.06588582,
        88.43980714,  88.12802665,  73.37558774,  89.19317848,
       105.76256275, 105.6684754 ,  90.43715823, 127.88267933,
        99.11806181, 115.43506271,  90.97513626,  69.09559124,
       108.05836998, 122.92391077,  76.25193188, 127.92907003,
       102.38685105, 113.19556256,  93.71756441, 114.30388416,
       105.38768085, 117.31497445, 116.78209733,  96.09483784,
       125.40259971, 114.49060894, 110.40674246, 106.5175395 ,
        91.88355894, 120.78137095, 112.52839802, 100.59283212,
       124.83935524,  99.01711994,  84.8836304 , 101.2169883 ,
        89.35684702,  95.75849193, 101.99507858, 109.39090843,
       130.77258522, 110.67521113, 108.76175786, 106.29573644,
        91.78813041,  74.94148024, 110.25280333,  76.37555728,
        90.3247024 ,  84.38017808, 100.5860791 , 105.31987326,
       119.19915426,  93.91624655,  87.98686586,  84.50757218,
       116.71159666, 101.15827991,  89.1991273 , 125.45288126,
        80.69905368,  99.97509758, 101.92960311, 101.9909653 ,
        95.98860519,  87.10020544, 103.11483952, 119.02981574,
        85.84408352, 114.64094243, 113.6336012 , 104.56673819,
        95.51602811, 119.40966338, 113.3708345 ,  99.6058354 ,
        95.49065835,  77.85760269, 118.06643461,  90.28240061,
        75.36809217, 108.99754533, 122.10285294,  86.71232847,
       109.65315336,  95.98374518,  90.74983658, 111.0063063 ,
       118.29024342, 107.56172528, 115.21574177,  87.9403522 ,
        59.68751672,  93.979101  ,  95.86496126,  88.02466462,
       121.78298607, 117.58914748, 108.50460735,  90.52143344,
       119.98074618,  88.71359514, 107.56461961,  99.20702268,
       120.95807182, 106.9111516 , 103.35615967,  88.86872261,
        89.41118592,  71.65999926,  79.39960215, 100.26624503,
       109.35500333, 118.71109664, 104.6911026 ,  72.05488301,
       104.90002202, 109.81583774, 104.98932818, 113.91312945,
       130.96174207, 120.86839205, 104.1812075 , 109.47066645,
       123.11104284, 119.77974167,  88.54556327,  85.77724201,
       105.43365223, 115.32880929, 110.38368485,  92.22051483,
        59.0747899 , 101.9556277 , 100.3024659 , 105.19044719,
        84.21536881,  97.53722597, 113.3658751 , 110.54986963,
        88.37379225, 106.17798303, 134.07566885,  79.01713607,
       105.86862303, 118.91220108,  88.59175646,  74.20742   ,
        92.88419357, 128.438284  , 117.33014515, 114.67454117,
        88.58420909, 111.68766086,  83.68249813, 117.69665497,
        92.03311513, 107.71807432, 113.32501959,  91.6957373 ,
        98.55418133, 119.95325821, 128.86256225, 117.58648057,
       101.20323643, 103.25153323, 124.63529191,  86.38760478,
        88.53645122,  97.22940257, 127.63363075, 100.17601125,
        99.26457266, 105.66706648,  94.03730771,  84.94219596,
        95.0614971 , 113.65222754, 105.56173911, 104.2173876 ,
        90.41196645,  78.79019734, 121.67166543,  88.85597454,
       100.70188184, 117.62130427, 109.4449795 , 114.0229273 ,
       117.20412661,  82.92117828,  95.45166796,  90.14109885,
       104.58697877,  91.48919567,  97.35809817,  96.545273  ,
        70.6338843 , 104.28537623,  75.68165023, 113.93088536,
       110.55218644,  82.98126365,  92.43412759,  86.55927663,
       127.71122916, 102.03798863,  78.36359093, 120.30476329,
        99.85083322, 114.55704124,  97.53668469,  89.70530999,
       109.22755621,  82.6894849 , 115.37626009, 134.68865422,
       116.55922228,  74.62044454, 100.42855183, 126.95424649,
       104.20595697,  99.43910043,  83.46958728, 117.03759018,
        92.15629897,  99.58447598,  97.57476431,  96.05965319,
       110.22824288, 104.17646764, 106.93924361, 121.70939512,
       101.373202  , 111.82325623,  99.04039492,  85.64792288,
       116.35429935, 113.11010134, 105.76489621, 108.68540459,
        88.93543619,  96.20498561,  98.8994623 ,  88.19906286,
        82.88775229, 101.51905572,  99.69395204, 100.42384525,
        88.51016706, 123.70844226, 109.19564888,  98.77995882,
        96.9957825 ,  97.59866916,  98.71468696,  76.0899157 ,
        82.15932067, 101.59204054, 108.23120517,  97.18441118,
       107.65583019,  82.73183183,  92.72263196,  97.12922704,
        76.3813464 , 121.32255497,  92.05920261,  89.8841027 ,
       100.44291919, 105.45721262,  95.06934496,  96.71431497,
       114.43753675, 106.72080725,  95.99497021, 117.77831322,
       101.72539792, 110.23262629,  93.37655028,  94.24024095,
        73.00107612,  81.90321681,  95.2987682 , 114.39904024,
        67.75998822, 100.59300294,  82.10351632, 110.18004422,
       116.51680636,  96.7227044 , 109.79597381, 104.23970467,
        83.49497882, 112.21025898,  80.58546604, 115.99067164,
       128.1168137 ,  99.43975448, 114.83141541, 110.57959079,
        92.38967488,  95.34530609,  96.73148649,  97.61601455,
       122.29688477, 120.59949243,  73.60607457, 119.20794377,
       133.70284569,  97.62666418, 117.83852432,  98.82367288,
       113.82977386, 106.53092336, 127.86479521, 105.07823291,
        87.84026818,  97.17001548, 111.98634448,  79.06484655,
       117.88061262, 109.66051609, 112.69844557, 129.49732443,
       109.84477813,  84.19553434,  90.15133195,  88.41693982,
        89.88287521,  89.49568187, 101.95836346,  74.19332329,
       128.75910319, 104.54386546,  96.1723579 , 105.5059294 ,
       105.01157326,  95.76081441, 100.24963755, 107.5853131 ,
        93.64984113, 107.45325603,  97.67922678, 100.1042609 ,
        97.40382024, 135.30901639, 114.87784577, 105.28455538,
       119.5944885 ,  98.80562686, 102.67255222,  81.83706916,
        71.45726677, 117.70560681,  74.93116041, 108.26445721,
        98.84401984, 120.3714111 ,  65.71186631, 106.73698773,
        99.80277159, 106.12360734, 100.27631445,  88.46850559,
        77.12004997, 109.43780584,  94.00753065, 109.34794499,
        80.75540322,  93.81593656,  84.8499736 ,  93.13154029,
        96.20877889, 115.12617387,  91.08320588,  71.47803892,
       121.84742374,  63.69634084, 123.47355875,  87.12159233,
        94.95998332,  83.16932634, 110.44374752, 115.98483885,
       104.83533833, 133.76486603, 102.2531251 ,  94.975401  ,
        97.74270549, 104.80893434,  92.46453884, 102.66446861,
       107.61507578, 105.63703571,  90.19020842, 105.59105206,
        85.90915627, 100.77799742,  98.54894437, 116.5916871 ,
       114.62482654,  94.13604582,  87.59480001, 117.05828451,
        82.91883476,  95.64301056,  75.71753947,  84.03331874,
        98.25771325, 117.37501818,  97.85323131, 108.28506685,
        74.18125474, 102.77288487, 120.28325543,  95.052106  ,
        73.04526423,  83.93808234, 114.24046351, 116.41903644,
       107.88823735,  95.29321419,  71.21725376,  82.77715208,
       115.5495471 ,  98.76778095, 126.36493418,  94.75670399,
       122.91364187, 103.71831493,  84.28635013,  98.26926083,
       134.18349929,  89.75829998,  95.44581626, 106.71842096,
       110.3197592 ,  69.19793083,  94.93735622,  94.65676132,
       126.05555146, 109.13370587, 109.49295064, 103.67110853,
        86.38779121,  80.22248287,  85.38588415,  70.55315254,
        89.78965106,  81.1590091 ,  79.30027886,  87.05207609,
        94.69432053, 107.31569735,  84.91009975, 101.92434981,
       107.94560625, 148.88564394,  93.74677245, 115.81684871,
       108.42737522, 108.61930794,  90.92407409, 113.5142557 ,
       121.73976861,  84.63396084, 101.30372113,  90.53144158,
       100.98932267,  91.58154902, 108.78700582,  77.28984481,
       114.09311307, 132.88760298,  82.48724102, 105.62096735,
       114.64663643,  93.52473672, 114.82758557,  90.33076639,
       102.21400972, 129.66850333,  83.62401449, 107.31617555,
       113.94919152, 121.1862789 ,  94.86034415,  83.71706028,
        87.70306825, 117.33336198,  70.36832233, 116.34299855,
        97.28493235,  93.34591995,  76.94305952,  97.3642038 ,
        98.56946701, 110.77792303, 122.76931162,  95.71299028,
        84.52729559,  74.09374162,  66.907704  , 110.27379185,
        89.63315154,  96.76283298,  85.98905552,  87.13773527,
       110.13350293,  87.28984828,  96.52852186, 100.89601497,
        71.5310286 , 107.72000731,  93.22010449, 111.62093048,
       113.69978363,  94.6619486 , 118.39710221, 121.29051598,
        89.85501803, 106.21095354,  91.67731572,  99.98656377,
       106.98724303, 108.77530933, 100.81564359, 105.13333362,
       100.49639056, 114.85505416, 101.41002382, 104.95508504,
       113.42042898,  85.84207819,  98.05694564,  81.81180074,
       120.35526091,  89.59824964,  63.80017642, 104.47363354,
        87.10013445, 113.70951376,  79.19436906,  79.17022122,
       118.52154806, 108.65041578,  82.60973909,  93.47992508,
        91.22844126,  71.49244918,  96.6822087 ,  93.29668987,
       136.35381761,  84.39114692,  93.07894874,  98.02122749,
       116.16522058,  81.67955567, 105.97772813,  98.46253373,
        93.76325907,  97.17577234,  74.95355873,  70.58748834,
       105.71375097, 124.03181241, 154.56851407,  95.12753131,
       113.56557658,  95.26443956, 129.56358843, 122.80344219,
        78.58367332, 123.44428954, 107.23416627, 100.43246709,
       103.95609968, 105.69615375,  81.22159656, 115.72996414,
        99.0204996 ,  95.39260625,  97.78548533, 112.14565451,
        91.42701129, 116.63715857,  98.62297554,  97.54424841,
       104.43825435,  81.44327687, 113.971366  ,  70.70452387,
       107.15783375, 110.90884191,  88.78570007,  89.75606711,
       112.33346729, 106.64759527, 113.96061099, 101.98222001,
       100.83281532,  98.55262703,  97.51122815,  92.04874124,
        93.34134745,  99.50492614, 121.62323726, 107.31108538,
        99.03669291, 102.37193465, 110.24721951, 121.11719421,
        78.17840134, 106.90493285,  71.89106202, 107.69363316,
       103.87997597,  99.69268932, 115.5902543 ,  80.30925281,
       113.66210694, 105.91695452,  86.62742602,  84.72926742,
        89.2471053 , 115.17487075, 107.05494185, 117.96887929,
        93.79977672, 113.5441985 , 116.93671537,  98.37794134,
        98.36001038, 105.07678783, 110.60084292,  76.97700545,
        92.66516338, 111.46094213, 123.78584394,  88.77324855,
        99.06861712, 104.5714997 , 103.97045575,  88.0905704 ,
        74.00137112, 114.31838511,  87.7596836 , 105.08403215,
       146.8819145 ,  98.61299612, 117.42615638,  85.44069936,
        71.12514063,  84.75503286,  89.62661625, 104.7570859 ,
       126.0966449 ,  78.05013281,  95.9683839 , 100.01729451,
        84.18469344,  92.99977385, 103.36843519,  97.06853425,
       119.31502847,  80.81898764, 103.51245148, 118.09223909,
        86.09622622, 104.74695619, 103.96454341, 108.84254612,
        73.71400247,  82.83647737,  85.14684331,  99.99278076,
        99.2100972 , 102.27208367, 125.92110853,  91.27673524,
        80.33564361,  98.19602398, 103.44476992, 104.99078029,
       117.60819   , 105.34556095,  92.91579182, 111.86016271,
       104.38273369, 119.34566101, 127.09119102,  77.91355713,
        81.52629586,  76.46385296,  68.97311164,  82.95913308,
       103.08159984,  80.43178054, 121.15205498, 101.61540069,
       109.51340091,  56.10244563,  98.69448732,  86.494743  ,
        83.94876657,  97.45485554,  83.81742723,  88.26382347,
       122.16871124, 101.88962346, 104.69093785, 101.82893014,
        93.49274428, 104.99800535,  95.546517  , 113.85697802,
       107.81023046, 108.53552495, 130.58301693, 112.13719044,
       114.19847511,  81.63057739,  92.60961283,  99.59274637,
        53.35965549,  98.28612647,  82.59026514, 105.43466572,
       107.70096836,  93.48634577, 104.75382008,  97.89694084,
        97.37848851, 113.38958608,  92.49818362, 111.65197913,
       112.97267615,  84.54066775, 112.49227118, 106.93916845,
        80.22930934,  99.14166974,  73.52362999,  82.38455959,
       114.59536881, 110.48062204, 102.74558021,  90.64665758,
       105.32946247,  76.71713776, 111.56451667,  97.06997513,
        78.07794648,  70.31541081, 117.17230771,  96.11854873,
       114.84779939, 122.66049696, 111.87757767,  90.19374355,
       107.35759155, 100.69549126, 112.42003798, 122.5072009 ,
        88.14875796, 115.24277161,  63.48672524, 114.5681461 ,
        77.48501163, 100.99868941, 108.55057498,  78.67196822,
       107.19703497, 114.72392572,  70.36888488,  64.46702481,
        81.76399281,  75.49915834,  90.14440975, 112.11942741,
       101.57514569, 100.4433113 ,  93.99643227, 100.30814779,
        91.22275023,  94.69029019, 101.76305923,  84.39785201,
        94.76160935, 107.49811887,  92.05253864,  81.15176916,
        96.52593052,  80.63313698, 133.01985686,  63.8928776 ,
       107.92082468, 105.75849525,  89.7367689 , 112.90244051,
        93.44935467,  95.04324182, 110.48394079,  84.95397023,
        62.53500145,  96.37416546, 114.03039976, 117.27027443,
       115.04834309,  91.29876732, 103.89615356,  90.54054691,
       108.54166494, 104.34837216,  83.67604737, 108.84631465,
       111.06095784,  99.16109663,  99.96327761, 102.23456766,
        99.52994272,  91.1022475 ,  88.70315403,  88.13817092,
        88.38845313, 105.07781234,  84.72534848, 103.30914921,
        81.45473694, 105.29883278, 128.81941522,  93.08712427,
       116.05265483, 115.25802407,  94.80567589, 117.29588622,
        84.51691083, 109.08542377,  90.30070993, 121.53665466,
       106.72640619, 109.80823621,  96.55992921, 121.5869757 ,
       100.62536955,  81.0584448 , 104.28634601,  94.67250594,
        75.17100447, 139.46799216,  95.70211682, 101.66668552,
        92.86038708, 110.51244617,  86.12652039,  72.89808666,
       106.97469898,  93.91297001, 112.25831848, 102.14031399,
       123.28482895, 129.66426989, 110.61603569,  93.36983543,
        85.02470321,  97.56463947, 111.09350987,  93.26987269,
        65.43243178, 113.05720336, 107.92873536,  73.67348316,
       125.55793711, 105.2986658 ,  99.16466688,  79.78553371,
        94.77075166, 107.00579232,  97.20378087, 119.81715889,
        95.92556539,  87.05179068,  99.38658549,  86.92084445,
       108.26574695,  82.02592745, 116.87935648, 114.67489277,
        87.1183353 ,  90.55199169,  88.98749697, 110.30759984,
        82.51454823,  98.14272697, 136.96573408,  89.32796519,
       100.82606477,  98.04218197, 121.54889128,  74.38701587,
        93.87347331, 111.36954816, 112.0124085 ,  94.88144936,
        81.42318643, 123.94374047, 118.91306465, 104.92045809,
       100.18060505, 108.09808946, 100.43456038,  87.43274935,
        88.04068591, 102.28131792, 105.44168445,  90.92989609,
       122.93948466, 110.95443254,  81.84226511,  87.15394078,
       135.83915386,  72.21321743, 112.10135691, 120.41540677,
       117.34614503, 106.16661998,  54.15331257, 101.97017117,
        90.73414993, 124.06095855, 106.47680627, 116.56720865,
        92.60650598,  83.20042742,  95.69891587,  78.00284703,
        71.16490263, 102.62041863, 101.14417733, 122.43674767,
        92.91598964,  91.50650502, 123.08720066,  95.51491665,
        97.48114577,  84.99970936,  80.27572844, 116.6547885 ])

Compute the **mean**, **median**, and **mode**

In [12]:
mean =np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)
print(mean)
print(median)
print(mode)

99.63333123830938
99.82905026937968
ModeResult(mode=array([47.68199818]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [8]:
min = np.min(samples)
print(min)
max = np.max(samples)
print(max)
q1 = np.percentile(samples,25)
print(q1)
q3 = np.percentile(samples,75)
print(q3)
iqr= stats.iqr(samples)
print(iqr)

53.35965548784427
154.56851407218454
89.78181328668701
110.55903752567548
20.777224238988467

Compute the **variance** and **standard deviation**

In [9]:
variance = np.var(samples)
print(variance)
std_dev = np.std(samples)
print(std_dev)

229.47567418525577
15.1484545147436

Compute the **skewness** and **kurtosis**

In [10]:
skewness = stats.skew(samples)
print(skewness)
kurtosis = stats.kurtosis(samples)
print(kurtosis)

-0.05312808314313685
-0.03354154183399993

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [11]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [12]:
y = np.array([1,2,3,4,5,6,7,8,9,10])
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [15]:
r = np.corrcoef(x, y)
r

array([[1., 1.],
       [1., 1.]])

## Pandas Correlation Calculation

Run the code below

In [16]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [22]:
r = pd.DataFrame([x,y])
r.corr(method="pearson")

     0    1    2    3    4    5    6    7    8    9
0  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
1  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
2  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
3  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
5  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
6 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
7 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
8 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
9 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [23]:
rho = r.corr(method="spearman")
print(rho)

     0    1    2    3    4    5    6    7    8    9
0  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
1  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
2  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
3  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
5  1.0  1.0  1.0  1.0  1.0  1.0 -1.0 -1.0 -1.0 -1.0
6 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
7 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
8 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0
9 -1.0 -1.0 -1.0 -1.0 -1.0 -1.0  1.0  1.0  1.0  1.0

## Seaborn Dataset Tips

Import Seaborn Library

In [24]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [25]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [27]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [28]:
stats.mode(tips)

ModeResult(mode=array([[13.42, 2.0, 'Male', 'No', 'Sat', 'Dinner', 2]], dtype=object), count=array([[  3,  33, 157, 151,  87, 176, 156]]))

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [30]:
tips.corr(method='pearson')

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000